<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Kuser\Module'                        => __DIR__ . '/Module.php',
    'Kuser\Controller\KuserController' => __DIR__ . '/src/Kuser/Controller/KuserController.php',
    'KuserTest\Framework\TestCase'        => __DIR__ . '/tests/Kuser/Framework/TestCase.php',
    'KuserTest\SampleTest'                => __DIR__ . '/tests/Kuser/SampleTest.php',
);
